//! The built-in encoding vectors: StandardEncoding and ISOLatin1Encoding,
//! per PLRM Appendix E, plus a glyph-name → Unicode table used when a
//! font file's own name table can't resolve a glyph name.
//!
//! Both encodings share the ASCII range (with Adobe's text-quote choices:
//! 0x27 is `quoteright`, 0x60 is `quoteleft` — not the ASCII apostrophe
//! and grave), and differ above 0x7f.

/// Names for codes 0x20..=0x7e, shared by both encodings.
const ASCII_NAMES: [&str; 95] = [
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quoteright",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "quoteleft",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
];

/// StandardEncoding above 0x7f (sparse; everything else is .notdef).
const STANDARD_HIGH: &[(u8, &str)] = &[
    (0o241, "exclamdown"),
    (0o242, "cent"),
    (0o243, "sterling"),
    (0o244, "fraction"),
    (0o245, "yen"),
    (0o246, "florin"),
    (0o247, "section"),
    (0o250, "currency"),
    (0o251, "quotesingle"),
    (0o252, "quotedblleft"),
    (0o253, "guillemotleft"),
    (0o254, "guilsinglleft"),
    (0o255, "guilsinglright"),
    (0o256, "fi"),
    (0o257, "fl"),
    (0o261, "endash"),
    (0o262, "dagger"),
    (0o263, "daggerdbl"),
    (0o264, "periodcentered"),
    (0o266, "paragraph"),
    (0o267, "bullet"),
    (0o270, "quotesinglbase"),
    (0o271, "quotedblbase"),
    (0o272, "quotedblright"),
    (0o273, "guillemotright"),
    (0o274, "ellipsis"),
    (0o275, "perthousand"),
    (0o277, "questiondown"),
    (0o301, "grave"),
    (0o302, "acute"),
    (0o303, "circumflex"),
    (0o304, "tilde"),
    (0o305, "macron"),
    (0o306, "breve"),
    (0o307, "dotaccent"),
    (0o310, "dieresis"),
    (0o312, "ring"),
    (0o313, "cedilla"),
    (0o315, "hungarumlaut"),
    (0o316, "ogonek"),
    (0o317, "caron"),
    (0o320, "emdash"),
    (0o341, "AE"),
    (0o343, "ordfeminine"),
    (0o350, "Lslash"),
    (0o351, "Oslash"),
    (0o352, "OE"),
    (0o353, "ordmasculine"),
    (0o361, "ae"),
    (0o365, "dotlessi"),
    (0o370, "lslash"),
    (0o371, "oslash"),
    (0o372, "oe"),
    (0o373, "germandbls"),
];

/// ISOLatin1Encoding above 0x7f (sparse). 0x90–0x9f is Adobe's accent
/// block; 0xa0 on is Latin-1 with Adobe glyph names.
const ISO_LATIN1_HIGH: &[(u8, &str)] = &[
    (0o220, "dotlessi"),
    (0o221, "grave"),
    (0o222, "acute"),
    (0o223, "circumflex"),
    (0o224, "tilde"),
    (0o225, "macron"),
    (0o226, "breve"),
    (0o227, "dotaccent"),
    (0o230, "dieresis"),
    (0o232, "ring"),
    (0o233, "cedilla"),
    (0o235, "hungarumlaut"),
    (0o236, "ogonek"),
    (0o237, "caron"),
    (0o240, "space"),
    (0o241, "exclamdown"),
    (0o242, "cent"),
    (0o243, "sterling"),
    (0o244, "currency"),
    (0o245, "yen"),
    (0o246, "brokenbar"),
    (0o247, "section"),
    (0o250, "dieresis"),
    (0o251, "copyright"),
    (0o252, "ordfeminine"),
    (0o253, "guillemotleft"),
    (0o254, "logicalnot"),
    (0o255, "hyphen"),
    (0o256, "registered"),
    (0o257, "macron"),
    (0o260, "degree"),
    (0o261, "plusminus"),
    (0o262, "twosuperior"),
    (0o263, "threesuperior"),
    (0o264, "acute"),
    (0o265, "mu"),
    (0o266, "paragraph"),
    (0o267, "periodcentered"),
    (0o270, "cedilla"),
    (0o271, "onesuperior"),
    (0o272, "ordmasculine"),
    (0o273, "guillemotright"),
    (0o274, "onequarter"),
    (0o275, "onehalf"),
    (0o276, "threequarters"),
    (0o277, "questiondown"),
    (0o300, "Agrave"),
    (0o301, "Aacute"),
    (0o302, "Acircumflex"),
    (0o303, "Atilde"),
    (0o304, "Adieresis"),
    (0o305, "Aring"),
    (0o306, "AE"),
    (0o307, "Ccedilla"),
    (0o310, "Egrave"),
    (0o311, "Eacute"),
    (0o312, "Ecircumflex"),
    (0o313, "Edieresis"),
    (0o314, "Igrave"),
    (0o315, "Iacute"),
    (0o316, "Icircumflex"),
    (0o317, "Idieresis"),
    (0o320, "Eth"),
    (0o321, "Ntilde"),
    (0o322, "Ograve"),
    (0o323, "Oacute"),
    (0o324, "Ocircumflex"),
    (0o325, "Otilde"),
    (0o326, "Odieresis"),
    (0o327, "multiply"),
    (0o330, "Oslash"),
    (0o331, "Ugrave"),
    (0o332, "Uacute"),
    (0o333, "Ucircumflex"),
    (0o334, "Udieresis"),
    (0o335, "Yacute"),
    (0o336, "Thorn"),
    (0o337, "germandbls"),
    (0o340, "agrave"),
    (0o341, "aacute"),
    (0o342, "acircumflex"),
    (0o343, "atilde"),
    (0o344, "adieresis"),
    (0o345, "aring"),
    (0o346, "ae"),
    (0o347, "ccedilla"),
    (0o350, "egrave"),
    (0o351, "eacute"),
    (0o352, "ecircumflex"),
    (0o353, "edieresis"),
    (0o354, "igrave"),
    (0o355, "iacute"),
    (0o356, "icircumflex"),
    (0o357, "idieresis"),
    (0o360, "eth"),
    (0o361, "ntilde"),
    (0o362, "ograve"),
    (0o363, "oacute"),
    (0o364, "ocircumflex"),
    (0o365, "otilde"),
    (0o366, "odieresis"),
    (0o367, "divide"),
    (0o370, "oslash"),
    (0o371, "ugrave"),
    (0o372, "uacute"),
    (0o373, "ucircumflex"),
    (0o374, "udieresis"),
    (0o375, "yacute"),
    (0o376, "thorn"),
    (0o377, "ydieresis"),
];

fn build(high: &[(u8, &'static str)]) -> [&'static str; 256] {
    let mut names = [".notdef"; 256];
    for (i, n) in ASCII_NAMES.into_iter().enumerate() {
        names[0x20 + i] = n;
    }
    for &(code, name) in high {
        names[code as usize] = name;
    }
    names
}

pub fn standard_encoding() -> [&'static str; 256] {
    build(STANDARD_HIGH)
}

pub fn iso_latin1_encoding() -> [&'static str; 256] {
    build(ISO_LATIN1_HIGH)
}

/// Glyph name → Unicode, for looking a glyph up through `cmap` when the
/// font's own name table doesn't know it. Covers every name in the two
/// encoding tables above; general AGL coverage isn't needed for that.
pub fn name_to_char(name: &str) -> Option<char> {
    // Single-character names (letters, digits used literally) map to
    // themselves.
    let mut chars = name.chars();
    if let (Some(c), None) = (chars.next(), chars.next()) {
        return Some(c);
    }
    // uniXXXX names, common in re-encoded found files.
    if let Some(hex) = name.strip_prefix("uni")
        && hex.len() == 4
        && let Ok(cp) = u32::from_str_radix(hex, 16)
    {
        return char::from_u32(cp);
    }
    let cp: u32 = match name {
        "space" => 0x20,
        "exclam" => '!' as u32,
        "quotedbl" => '"' as u32,
        "numbersign" => '#' as u32,
        "dollar" => '$' as u32,
        "percent" => '%' as u32,
        "ampersand" => '&' as u32,
        "quotesingle" => 0x27,
        "parenleft" => '(' as u32,
        "parenright" => ')' as u32,
        "asterisk" => '*' as u32,
        "plus" => '+' as u32,
        "comma" => ',' as u32,
        "hyphen" => '-' as u32,
        "period" => '.' as u32,
        "slash" => '/' as u32,
        "zero" => '0' as u32,
        "one" => '1' as u32,
        "two" => '2' as u32,
        "three" => '3' as u32,
        "four" => '4' as u32,
        "five" => '5' as u32,
        "six" => '6' as u32,
        "seven" => '7' as u32,
        "eight" => '8' as u32,
        "nine" => '9' as u32,
        "colon" => ':' as u32,
        "semicolon" => ';' as u32,
        "less" => '<' as u32,
        "equal" => '=' as u32,
        "greater" => '>' as u32,
        "question" => '?' as u32,
        "at" => '@' as u32,
        "bracketleft" => '[' as u32,
        "backslash" => '\\' as u32,
        "bracketright" => ']' as u32,
        "asciicircum" => '^' as u32,
        "underscore" => '_' as u32,
        "grave" => 0x60,
        "braceleft" => '{' as u32,
        "bar" => '|' as u32,
        "braceright" => '}' as u32,
        "asciitilde" => '~' as u32,
        "quoteleft" => 0x2018,
        "quoteright" => 0x2019,
        "quotesinglbase" => 0x201A,
        "quotedblleft" => 0x201C,
        "quotedblright" => 0x201D,
        "quotedblbase" => 0x201E,
        "exclamdown" => 0xA1,
        "cent" => 0xA2,
        "sterling" => 0xA3,
        "currency" => 0xA4,
        "yen" => 0xA5,
        "brokenbar" => 0xA6,
        "section" => 0xA7,
        "dieresis" => 0xA8,
        "copyright" => 0xA9,
        "ordfeminine" => 0xAA,
        "guillemotleft" => 0xAB,
        "logicalnot" => 0xAC,
        "registered" => 0xAE,
        "macron" => 0xAF,
        "degree" => 0xB0,
        "plusminus" => 0xB1,
        "twosuperior" => 0xB2,
        "threesuperior" => 0xB3,
        "acute" => 0xB4,
        "mu" => 0xB5,
        "paragraph" => 0xB6,
        "periodcentered" => 0xB7,
        "cedilla" => 0xB8,
        "onesuperior" => 0xB9,
        "ordmasculine" => 0xBA,
        "guillemotright" => 0xBB,
        "onequarter" => 0xBC,
        "onehalf" => 0xBD,
        "threequarters" => 0xBE,
        "questiondown" => 0xBF,
        "Agrave" => 0xC0,
        "Aacute" => 0xC1,
        "Acircumflex" => 0xC2,
        "Atilde" => 0xC3,
        "Adieresis" => 0xC4,
        "Aring" => 0xC5,
        "AE" => 0xC6,
        "Ccedilla" => 0xC7,
        "Egrave" => 0xC8,
        "Eacute" => 0xC9,
        "Ecircumflex" => 0xCA,
        "Edieresis" => 0xCB,
        "Igrave" => 0xCC,
        "Iacute" => 0xCD,
        "Icircumflex" => 0xCE,
        "Idieresis" => 0xCF,
        "Eth" => 0xD0,
        "Ntilde" => 0xD1,
        "Ograve" => 0xD2,
        "Oacute" => 0xD3,
        "Ocircumflex" => 0xD4,
        "Otilde" => 0xD5,
        "Odieresis" => 0xD6,
        "multiply" => 0xD7,
        "Oslash" => 0xD8,
        "Ugrave" => 0xD9,
        "Uacute" => 0xDA,
        "Ucircumflex" => 0xDB,
        "Udieresis" => 0xDC,
        "Yacute" => 0xDD,
        "Thorn" => 0xDE,
        "germandbls" => 0xDF,
        "agrave" => 0xE0,
        "aacute" => 0xE1,
        "acircumflex" => 0xE2,
        "atilde" => 0xE3,
        "adieresis" => 0xE4,
        "aring" => 0xE5,
        "ae" => 0xE6,
        "ccedilla" => 0xE7,
        "egrave" => 0xE8,
        "eacute" => 0xE9,
        "ecircumflex" => 0xEA,
        "edieresis" => 0xEB,
        "igrave" => 0xEC,
        "iacute" => 0xED,
        "icircumflex" => 0xEE,
        "idieresis" => 0xEF,
        "eth" => 0xF0,
        "ntilde" => 0xF1,
        "ograve" => 0xF2,
        "oacute" => 0xF3,
        "ocircumflex" => 0xF4,
        "otilde" => 0xF5,
        "odieresis" => 0xF6,
        "divide" => 0xF7,
        "oslash" => 0xF8,
        "ugrave" => 0xF9,
        "uacute" => 0xFA,
        "ucircumflex" => 0xFB,
        "udieresis" => 0xFC,
        "yacute" => 0xFD,
        "thorn" => 0xFE,
        "ydieresis" => 0xFF,
        "florin" => 0x192,
        "fraction" => 0x2044,
        "fi" => 0xFB01,
        "fl" => 0xFB02,
        "endash" => 0x2013,
        "emdash" => 0x2014,
        "dagger" => 0x2020,
        "daggerdbl" => 0x2021,
        "bullet" => 0x2022,
        "ellipsis" => 0x2026,
        "perthousand" => 0x2030,
        "guilsinglleft" => 0x2039,
        "guilsinglright" => 0x203A,
        "circumflex" => 0x2C6,
        "caron" => 0x2C7,
        "breve" => 0x2D8,
        "dotaccent" => 0x2D9,
        "ring" => 0x2DA,
        "ogonek" => 0x2DB,
        "tilde" => 0x2DC,
        "hungarumlaut" => 0x2DD,
        "dotlessi" => 0x131,
        "Lslash" => 0x141,
        "lslash" => 0x142,
        "OE" => 0x152,
        "oe" => 0x153,
        _ => return None,
    };
    char::from_u32(cp)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ascii_range_is_dense_and_shared() {
        let std = standard_encoding();
        let iso = iso_latin1_encoding();
        for c in 0x20..0x7f {
            assert_ne!(std[c], ".notdef", "standard {c:#x}");
            assert_eq!(std[c], iso[c], "ascii range shared at {c:#x}");
        }
        assert_eq!(std[b'A' as usize], "A");
        assert_eq!(std[0x27], "quoteright");
        assert_eq!(std[0x60], "quoteleft");
    }

    #[test]
    fn high_ranges_differ_per_appendix_e() {
        let std = standard_encoding();
        let iso = iso_latin1_encoding();
        assert_eq!(std[0o251], "quotesingle");
        assert_eq!(std[0o260], ".notdef");
        assert_eq!(std[0o320], "emdash");
        assert_eq!(iso[0o351], "eacute");
        assert_eq!(iso[0o240], "space");
        assert_eq!(iso[0o255], "hyphen");
    }

    #[test]
    fn every_encoded_name_has_a_unicode_fallback() {
        for name in standard_encoding()
            .iter()
            .chain(iso_latin1_encoding().iter())
        {
            if *name != ".notdef" {
                assert!(name_to_char(name).is_some(), "no unicode for {name}");
            }
        }
    }
}
